"""create official assignment table

Revision ID: 48ec4764e4d2
Revises: f7d88b3bb91d
Create Date: 2026-09-27 13:46:42.459117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ec4764e4d2'
down_revision: Union[str, Sequence[str], None] = 'f7d88b3bb91d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('official_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=False),
    sa.Column('assignment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['official_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_official_assignments_id'), 'official_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_official_assignments_match_id'), 'official_assignments', ['match_id'], unique=False)
    op.create_index(op.f('ix_official_assignments_official_id'), 'official_assignments', ['official_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_official_assignments_official_id'), table_name='official_assignments')
    op.drop_index(op.f('ix_official_assignments_match_id'), table_name='official_assignments')
    op.drop_index(op.f('ix_official_assignments_id'), table_name='official_assignments')
    op.drop_table('official_assignments')
    # ### end Alembic commands ###
