"""allow empty teams in matches

Revision ID: 89fd60a36a22
Revises: bd8b562ed7fc
Create Date: 2026-10-07 23:59:33.460478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89fd60a36a22'
down_revision: Union[str, Sequence[str], None] = 'bd8b562ed7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'team_a_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('matches', 'team_b_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'team_b_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('matches', 'team_a_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
