"""add resolution to disputes

Revision ID: 908b6483adb0
Revises: d3d14396792b
Create Date: 2026-10-09 15:50:45.209373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '908b6483adb0'
down_revision: Union[str, Sequence[str], None] = 'd3d14396792b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disputes', sa.Column('resolution', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disputes', 'resolution')
    # ### end Alembic commands ###
