"""add unique constraint on official assignments and check constraint on match teams

Revision ID: 9c8ec704312d
Revises: 9d0b2b8f89ae
Create Date: 2026-09-27 23:45:00.430546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8ec704312d'
down_revision: Union[str, Sequence[str], None] = '9d0b2b8f89ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_official_assignment_match_official_type', 'official_assignments', ['match_id', 'official_id', 'assignment_type'])
    op.create_check_constraint('ck_match_team_a_not_team_b', 'matches', 'team_a_id != team_b_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_match_team_a_not_team_b', 'matches', type_='check')
    op.drop_constraint('uq_official_assignment_match_official_type', 'official_assignments', type_='unique')
    # ### end Alembic commands ###

