"""add dispute status history

Revision ID: aff276b95d35
Revises: b51c3d381779
Create Date: 2026-10-09 22:06:36.052455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aff276b95d35'
down_revision: Union[str, Sequence[str], None] = 'b51c3d381779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispute_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispute_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=False),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispute_status_history_changed_by'), 'dispute_status_history', ['changed_by'], unique=False)
    op.create_index(op.f('ix_dispute_status_history_dispute_id'), 'dispute_status_history', ['dispute_id'], unique=False)
    op.create_index(op.f('ix_dispute_status_history_id'), 'dispute_status_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispute_status_history_id'), table_name='dispute_status_history')
    op.drop_index(op.f('ix_dispute_status_history_dispute_id'), table_name='dispute_status_history')
    op.drop_index(op.f('ix_dispute_status_history_changed_by'), table_name='dispute_status_history')
    op.drop_table('dispute_status_history')
    # ### end Alembic commands ###
