"""add fixtures published flag

Revision ID: ba9ac504a6f6
Revises: d3d14396792b
Create Date: 2026-10-09 15:36:49.108989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9ac504a6f6'
down_revision: Union[str, Sequence[str], None] = 'd3d14396792b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('fixtures_published', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'fixtures_published')
    # ### end Alembic commands ###
