"""add tournament rounds and match progression

Revision ID: bd8b562ed7fc
Revises: 4320e1572519
Create Date: 2026-10-07 23:43:47.221653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd8b562ed7fc'
down_revision: Union[str, Sequence[str], None] = '4320e1572519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('bracket_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'round_number', 'bracket_type', name='uq_tournament_round_order')
    )
    op.create_index(op.f('ix_tournament_rounds_id'), 'tournament_rounds', ['id'], unique=False)
    op.create_index(op.f('ix_tournament_rounds_tournament_id'), 'tournament_rounds', ['tournament_id'], unique=False)
    op.add_column('matches', sa.Column('round_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('winner_next_match_id', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('loser_next_match_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_matches_loser_next_match_id'), 'matches', ['loser_next_match_id'], unique=False)
    op.create_index(op.f('ix_matches_round_id'), 'matches', ['round_id'], unique=False)
    op.create_index(op.f('ix_matches_winner_next_match_id'), 'matches', ['winner_next_match_id'], unique=False)
    op.create_foreign_key('fk_matches_loser_next_match_id_matches', 'matches', 'matches', ['loser_next_match_id'], ['id'])
    op.create_foreign_key('fk_matches_round_id_tournament_rounds', 'matches', 'tournament_rounds', ['round_id'], ['id'])
    op.create_foreign_key('fk_matches_winner_next_match_id_matches', 'matches', 'matches', ['winner_next_match_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(
        'fk_matches_loser_next_match_id_matches',
        'matches',
        type_='foreignkey'
    )
    op.drop_constraint(
        'fk_matches_round_id_tournament_rounds',
        'matches',
        type_='foreignkey'
    )
    op.drop_constraint(
        'fk_matches_winner_next_match_id_matches',
        'matches',
        type_='foreignkey'
    )
    op.drop_index(
        op.f('ix_matches_winner_next_match_id'),
        table_name='matches'
    )
    op.drop_index(
        op.f('ix_matches_round_id'),
        table_name='matches'
    )
    op.drop_index(
        op.f('ix_matches_loser_next_match_id'),
        table_name='matches'
    )
    op.drop_column('matches', 'loser_next_match_id')
    op.drop_column('matches', 'winner_next_match_id')
    op.drop_column('matches', 'round_id')
    op.drop_index(
        op.f('ix_tournament_rounds_tournament_id'),
        table_name='tournament_rounds'
    )
    op.drop_index(
        op.f('ix_tournament_rounds_id'),
        table_name='tournament_rounds'
    )
    op.drop_table('tournament_rounds')
