"""create tournament team relationship

Revision ID: d2d642ae976e
Revises: 5e4b92d189a8
Create Date: 2026-09-27 15:05:41.288224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d642ae976e'
down_revision: Union[str, Sequence[str], None] = '5e4b92d189a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
       'tournament_id',
       'team_id',
       name='uq_tournament_team',
    ),
    )
    op.create_index(op.f('ix_tournament_teams_id'), 'tournament_teams', ['id'], unique=False)
    op.create_index(op.f('ix_tournament_teams_team_id'), 'tournament_teams', ['team_id'], unique=False)
    op.create_index(op.f('ix_tournament_teams_tournament_id'), 'tournament_teams', ['tournament_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tournament_teams_tournament_id'), table_name='tournament_teams')
    op.drop_index(op.f('ix_tournament_teams_team_id'), table_name='tournament_teams')
    op.drop_index(op.f('ix_tournament_teams_id'), table_name='tournament_teams')
    op.drop_table('tournament_teams')
    # ### end Alembic commands ###
